apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app-develop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: development 
  source:
    repoURL: https://github.com/gonzaloacosta/gitops-voting-app-develop.git
    targetRevision: HEAD 
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: development 
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

