apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: _APP_ID_
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: previews
  source:
    path: helm
    repoURL: https://github.com/gonzaloacosta/_REPO_.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: _IMAGE_TAG_
        ingress:
          host: _HOSTNAME_
      version: v3
  destination:
    namespace: _APP_ID_
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
